services:
  fast_api_app:
    container_name: github_app
    build: .
    volumes:
       - ./app:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    # Для локальной разработки и тестирования достаточно --workers 1
    command: uvicorn main:create_app --workers 1 --host ${APP_HOST}
    # restart: unless-stopped